### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/pyret#1]
Overall documentation for building an Exercism track lives at https://exercism.org/docs/building/tracks/new

This issue helps keep track of the tasks you're working on towards launching this track.

The next steps are:

- [x] [Join our community](https://exercism.org/docs/building/tracks/new/join-our-community)
- [x] [Select programming language variant](https://exercism.org/docs/building/tracks/new/select-programming-language-variant) (if applicable)
- [x] [Select testing framework](https://exercism.org/docs/building/tracks/new/select-testing-framework)
- [x] [Add the first exercise](https://exercism.org/docs/building/tracks/new/add-first-exercise)
- [x] [Add initial exercises](https://exercism.org/docs/building/tracks/new/add-initial-exercises)
- [x] [Setup Continuous Integration](https://exercism.org/docs/building/tracks/new/setup-continuous-integration)
- [x] [Prepare for launch](https://exercism.org/docs/building/tracks/new/prepare-for-launch)
- [x] [Find Maintainers](https://exercism.org/docs/building/tracks/new/find-maintainers)
- [ ] [Launch!](https://exercism.org/docs/building/tracks/new/launch)
- [x] [Implement tooling](https://exercism.org/docs/building/tracks/new/implement-tooling)
- [x] [Prepare for open source contributions from strangers](https://exercism.org/docs/building/tracks/new/prepare-for-contributions)

Once you've finished a task, you can check them in this list.

## Questions

Please ask if you have any questions or if anything is confusing!

**Comment by BNAndras** [comment]
We're getting pretty close. I count 16 exercises done besides hello-world with another two for Bethany's review when she has time. I requested the track icon last week so we just need to work out the Docker kinks for the CI.

**Comment by BNAndras** [comment]
@kytrinyx, as of this morning, we're pretty close to launch. I just need to make another pass through the track documents. Do I need a track icon before launch? I made a request at https://github.com/exercism/website-icons/issues/157, but if I need to wait, that's fine. I have some more exercises I can port.

**Comment by BNAndras** [comment]
@ErikSchierboom, when you have a chance, can you take a look at the track? No rush, but I think we're largely there. I was considering upgrading the test runner to v2, but I won't get to it for a few weeks. v1 is likely enough for now.

**Comment by ErikSchierboom** [comment]
@BNAndras I've looked at the track and tested a couple of exercises, and I think we're good to go!

**Comment by BNAndras** [comment]
All merged exercises and ones still under review have pending test support so I think we're ready for another review once the test runner image is bumped to pyret-npm 0.27 per [exercism/pyret-test-runner#16](https://github.com/exercism/pyret-test-runner/issues/18).

**Comment by ErikSchierboom** [comment]
I've commented on that test runner issue. Once the version has been bumped, I'll give it another look.

**Comment by BNAndras** [comment]
Isaac noted last month that the documentation around the test runner and printing/spying could be restructured. For example, at the moment, I explain what the test runner does with the test suite, but I should be more explicit and show how to work with the test suite like turning tests on/off. I'll work on that the next few days.

**Comment by BNAndras** [comment]
Documentation is updated. I think we're ready for a final review.

**Comment by BNAndras** [comment]
@ErikSchierboom, the documentation is updated. I think we're ready for a final review.

**Comment by ErikSchierboom** [comment]
Okay! I'll have a look.

**Comment by ErikSchierboom** [comment]
I think we're good to go! Feel free to open a PR to set the track to active.
